### ISSUE TITLE
Something about datasets processing

### ISSUE THREAD

**Issue by alvin528** [SSSohn/ltcf#1]
Hello, I am very interested in this field after reading your paper published in ECCV2020, and now I want to apply this idea to the real world. Could you please provide your code for the datasets processing part? I'd like to refer to it. Thanks a lot.

**Comment by SSSohn** [comment]
Hi @alvin528, you can find this in the Models folder.

**Comment by alvin528** [comment]
> Hi @alvin528, you can find this in the Models folder.

Thank you very much for your reply, I may not express it clearly enough. In fact, what I want is the code to make the datasets, for example, the code for calculating the G and Y sets. I wonder if it is convenient for you to give me a copy?

**Comment by SSSohn** [comment]
G can be computed using Dijkstra's algorithm combined with Theta* and the Y needs to be simulated. We eventually plan to release our simulator, but not in the near future. Depending on the acceptance of a manuscript that is currently under review, we may release an additional dataset at the end of June, which simulates crowd scenarios in a wider variety of environments than the ones in this dataset.
